# Generated by Django 3.2.5 on 2021-08-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Radios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'radios',
                'managed': True,
            },
        ),
    ]
